### ISSUE TITLE
Make these tools Python 2/3 compatible.

### ISSUE THREAD

**Issue by bcipolli** [censusreporter/census-shapefile-utils#1]
Cool tools, but doesn't run on Python 3! :o

**Comment by bcipolli** [comment]
(note: I'm working on this while using the tool. Goal: Python 3 compatibility will require `six`, Python 2 will remain without any dependencies.)

**Comment by ryanpitts** [comment]
closed in https://github.com/censusreporter/census-shapefile-utils/pull/6
